// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opmqenbpoypcrwpjhskf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbXFlbmJwb3lwY3J3cGpoc2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5ODI3NjIsImV4cCI6MjA1OTU1ODc2Mn0.qU3NmPMiLHTYzhWw4UK-HyBVgzSknQ0rLY7ofrUWKnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);